all: uaf_basic uaf_basic_2 uaf_challenge

uaf_basic:
	gcc -o uaf_basic uaf_basic.c
	gcc -o uaf_basic_2 uaf_basic_2.c
	gcc -g -o uaf_challenge uaf_challenge.c

clean:
	rm uaf_basic uaf_basic_2 uaf_challenge
