all: 3-2-hello 3-5-addressing 3-6-stack 3-6-function 3-7-segment

3-2-hello:
	nasm -f bin -o 3-2-hello.bin 3-2-hello.asm

3-5-addressing:
	nasm -f bin -o 3-5-addressing.bin 3-5-addressing.asm

3-6-stack:
	nasm -f bin -o 3-6-stack.bin 3-6-stack.asm

3-6-function:
	nasm -f bin -o 3-6-function.bin 3-6-function.asm

3-7-segment:
	nasm -f bin -o 3-7-segment.bin 3-7-segment.asm

clean:
	rm *.bin
