all: 0 1 2 3 4 5 6 7 8 9 10

0: 0-main.c
	gcc -Wall -Wextra -pedantic -Werror 0-main.c -o 0

1: 1-main.c
	gcc -Wall -Wextra -pedantic -Werror 1-main.c -o 1

2: 2-main.c
	gcc -Wall -Wextra -pedantic -Werror 2-main.c -o 2

3: 3-main.c
	gcc -Wall -Wextra -pedantic -Werror 3-main.c -o 3

4: 4-main.c
	gcc -Wall -Wextra -pedantic -Werror 4-main.c -o 4

5: 5-main.c
	gcc -Wall -Wextra -pedantic -Werror 5-main.c -o 5

6: 6-main.c
	gcc -Wall -Wextra -pedantic -Werror 6-main.c -o 6

7: 7-main.c
	gcc -Wall -Wextra -pedantic -Werror 7-main.c -o 7

8: 8-main.c
	gcc -Wall -Wextra -pedantic -Werror 8-main.c -o 8

9: 9-main.c
	gcc -Wall -Wextra -pedantic -Werror 9-main.c -o 9

10: 10-main.c
	gcc -Wall -Wextra -pedantic -Werror 10-main.c -o 10

clean:
	rm 0 1 2 3 4 5 6 7 8 9 10
